/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import TableModels.PrescriptionTableModel;
import entity.Company;
import entity.Medicine;
import entity.Patient;
import entity.PatientService;
import entity.Prescription;
import java.sql.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import services.CommonServices;
import javax.swing.SpinnerModel;

/**
 *
 * @author Suhail Alam
 */
public class NewPrescriptionForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewPatient
     */
    private Vector<Patient> vectorPatients;
    private Vector<Company> vectorCompanies;
    private Vector<Medicine> vectorMedicines;
    private Vector<String> vectorPacking;

    private CommonServices commonServices;
    private PatientService patientService;

    private Vector<Prescription> vectorPrescription;

    public NewPrescriptionForm() {
        initComponents();
        commonServices = new CommonServices();
        patientService = new PatientService();

        vectorPrescription = new Vector<Prescription>();

        vectorCompanies = commonServices.getVectorCompanies();
        vectorPatients = commonServices.getVectorPatients();

        DefaultComboBoxModel modelCompanies = new DefaultComboBoxModel(vectorCompanies);
        DefaultComboBoxModel modelPatients = new DefaultComboBoxModel(vectorPatients);

        cmbSelectCompany.setModel(modelCompanies);
        cmbSelectPatient.setModel(modelPatients);

        long currentTimeMilli = System.currentTimeMillis();
        System.out.println(currentTimeMilli);

        Date date = new Date(currentTimeMilli);

        
        jdDateChooser.setDate(date);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbSelectCompany = new javax.swing.JComboBox<>();
        cmbSelectMedicine = new javax.swing.JComboBox<>();
        cmbSelectPacking = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        txtDosage = new javax.swing.JTextField();
        btnAddToList = new javax.swing.JButton();
        btnClearList = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearchPatient = new javax.swing.JTextField();
        cmbSelectPatient = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtNewPrescription = new javax.swing.JTable();
        btnFinishPrescription = new javax.swing.JButton();
        jdDateChooser = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("New Prescription Form");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select Company");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Medicine");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Select Packing");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dosage");

        cmbSelectCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectCompanyActionPerformed(evt);
            }
        });

        cmbSelectMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectMedicineActionPerformed(evt);
            }
        });

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));

        btnAddToList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddToList.setText("Add To List");
        btnAddToList.setToolTipText("");
        btnAddToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToListActionPerformed(evt);
            }
        });

        btnClearList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClearList.setText("Clear List");
        btnClearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Search Patient");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Select Patient");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date");

        txtSearchPatient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchPatientKeyReleased(evt);
            }
        });

        jtNewPrescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company", "Medicine", "Packing", "Quantity", "Dosage", "Date"
            }
        ));
        jtNewPrescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtNewPrescriptionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtNewPrescription);

        btnFinishPrescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFinishPrescription.setText("Finish Prescription");
        btnFinishPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishPrescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinishPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSelectCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSelectMedicine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSelectPacking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtDosage)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddToList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(cmbSelectPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSelectCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbSelectMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSelectPacking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinishPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListActionPerformed
        vectorPrescription.removeAllElements();
        PrescriptionTableModel priscriptionTableModel = new PrescriptionTableModel(vectorPrescription);
        jtNewPrescription.setModel(priscriptionTableModel);
    }//GEN-LAST:event_btnClearListActionPerformed

    private void txtSearchPatientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPatientKeyReleased
        String patientName = txtSearchPatient.getText();

        vectorPatients = commonServices.getVectorPatients(patientName);

        DefaultComboBoxModel modelPatients = new DefaultComboBoxModel(vectorPatients);
        cmbSelectPatient.setModel(modelPatients);
    }//GEN-LAST:event_txtSearchPatientKeyReleased

    private void cmbSelectCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectCompanyActionPerformed
        Company company = (Company) cmbSelectCompany.getSelectedItem();
        vectorMedicines = commonServices.getCompanyMedicines(company);

        DefaultComboBoxModel modelMedicines = new DefaultComboBoxModel(vectorMedicines);
        cmbSelectMedicine.setModel(modelMedicines);

    }//GEN-LAST:event_cmbSelectCompanyActionPerformed

    private void cmbSelectMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectMedicineActionPerformed
        Medicine medcine = (Medicine) cmbSelectMedicine.getSelectedItem();

        vectorPacking = commonServices.getMedicinePacking(medcine);
        DefaultComboBoxModel modelPacking = new DefaultComboBoxModel(vectorPacking);
        cmbSelectPacking.setModel(modelPacking);
    }//GEN-LAST:event_cmbSelectMedicineActionPerformed

    private void btnAddToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToListActionPerformed
        Company company = (Company) cmbSelectCompany.getSelectedItem();
        Medicine medicine = (Medicine) cmbSelectMedicine.getSelectedItem();
        String Packing = cmbSelectPacking.getSelectedItem().toString();

        String dosage = txtDosage.getText();
        
        String value = spnQuantity.getValue().toString();
        int quantity = Integer.parseInt(value);

        medicine.setCompany(company);
        medicine.setPacking(Packing);

        int year = jdDateChooser.getCalendar().get(1);
        int day = jdDateChooser.getCalendar().get(5);
        int month = jdDateChooser.getCalendar().get(2) + 1;
        
        String currentMonth = "";
        String currentDay = "";
        
        if(day<10){
            currentDay = "0" + day;
        }else{
            currentDay = ""+day;
        }
        if(month<10){
            currentMonth = "0" + month;
        }else{
            currentMonth = ""+ month;
        }

        String selectedDate = year + "-" + currentMonth + "-" + currentDay;
        
        Prescription prescription = new Prescription();
        
        prescription.setDosage(dosage);
        prescription.setMedicine(medicine);
        prescription.setPrescriptionDate(selectedDate);
        prescription.setQuantity(quantity);
        
        vectorPrescription.add(prescription);
        
        PrescriptionTableModel prescriptionTabelModel = new PrescriptionTableModel(vectorPrescription);
        jtNewPrescription.setModel(prescriptionTabelModel);


    }//GEN-LAST:event_btnAddToListActionPerformed

    private void btnFinishPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishPrescriptionActionPerformed
     if(vectorPrescription.size()>0){
         Patient patient = (Patient) cmbSelectPatient.getSelectedItem();
         
         patientService.saveNewPrescription(patient, vectorPrescription);
     }else{
         JOptionPane.showMessageDialog(this, "Empty Data Cannot Be Stored");
     }
    }//GEN-LAST:event_btnFinishPrescriptionActionPerformed

    private void jtNewPrescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNewPrescriptionMouseClicked
      int selectedRow = jtNewPrescription.getSelectedRow();
      
      int choice = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Delete This Row");
      
      if(choice == 0){
          vectorPrescription.removeElementAt(selectedRow);
          PrescriptionTableModel prescriptionTableModel = new PrescriptionTableModel(vectorPrescription);
          jtNewPrescription.setModel(prescriptionTableModel);
      }
      
    }//GEN-LAST:event_jtNewPrescriptionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToList;
    private javax.swing.JButton btnClearList;
    private javax.swing.JButton btnFinishPrescription;
    private javax.swing.JComboBox<String> cmbSelectCompany;
    private javax.swing.JComboBox<String> cmbSelectMedicine;
    private javax.swing.JComboBox<String> cmbSelectPacking;
    private javax.swing.JComboBox<String> cmbSelectPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdDateChooser;
    private javax.swing.JTable jtNewPrescription;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtSearchPatient;
    // End of variables declaration//GEN-END:variables
}
